version: "2"

# same as
# docker run -p 80:4000 -v $(pwd):/site bretfisher/jekyll-serve

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ADAFRUIT_IO_USERNAME=hugholousk
      - ADAFRUIT_IO_KEY=aio_JBeD438tFIYPGnSosgNRkzsj5eJL
    ports:
      - "0.0.0.0:8000:8000"
