version: "2"

services:
  smartfarm:
    image: hugholousk/smartfarm
    volumes:
      - ./mysite:/usr/src/app/mysite
    environment:
      - ADAFRUIT_IO_USERNAME=hugholousk
      - ADAFRUIT_IO_KEY=aio_iEkC47ECe0eCfnXWAJz64sNDbJZk
    ports:
      - "0.0.0.0:8000:8000"
