version: "2"

services:
  smartfarm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./mysite/db.sqlite3:/usr/src/app/mysite/db.sqlite3
    environment:
      - ADAFRUIT_IO_USERNAME=hugholousk
      - ADAFRUIT_IO_KEY=aio_JBeD438tFIYPGnSosgNRkzsj5eJL
    ports:
      - "0.0.0.0:8000:8000"
