# Generated by Django 3.2.2 on 2021-05-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Device',
        ),
    ]
