# Generated by Django 3.2.2 on 2021-05-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
