# Generated by Django 3.2.2 on 2021-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_device_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_type',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='key',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='value',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
