# Generated by Django 3.2.2 on 2021-05-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_device_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
